apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingress-rabbit
    namespace: project
    annotations:
        kubernetes.io/ingress.class: gloo
spec:
    rules:
    - http:
          paths:
          - path: /.*
            backend:
                serviceName: service-rabbit
                servicePort: 8082
