apiVersion: v1
kind: Service
metadata:
    name: lab-service
    namespace: project
spec:
    selector:
        app: lab
    ports:
        - port: 5000
          targetPort: 5000
    type: ClusterIP
